# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Documentation
    url: docs/
    weight: 1
  - name: Books
    url: books/
    weight: 2

sidebar:
  - identifier: more
    name: About me
    params:
      type: separator
    weight: 1
  - identifier: Github
    name: "Github ↗"
    url: "https://github.com/2peopledesu/"
    weight: 2
  - identifier: linkedin
    name: "linkedin ↗"
    url: "https://www.linkedin.com/in/myungyong-lee-a638b8157/"
    weight: 3
  - identifier: Blog
    name: "Blog ↗"
    url: "https://imap143.com/"
    weight: 4
  - identifier: Resume
    name: "Resume ↗"
    url: "https://resume.imap143.com/"
    weight: 5
