# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: blue

# SEO
marketing:
  seo:
    site_type: Documentation
    local_business_type: 'Education'
    org_name: 'Spring Boot Korean Documentation'
    description: '스프링 부트(Spring Boot) 공식 레퍼런스 문서의 한국어 번역본입니다.'
    twitter: '2peopledesu'
  analytics:
    google_analytics: 'G-75913D88BE'
    google_tag_manager: 'GTM-MGZKBR5P'
    microsoft_clarity: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "2peopledesu"
      # Logo filename in `assets/media/` folder
    show_search: true
    show_theme_chooser: true

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/2peopledesu/Spring-docs-to-korean/'
    branch: 'main'
  feedback:
    responses:
      positive: 'Glad to hear it! [Any ideas for improvements?](https://github.com/<USERNAME>/<REPO>/issues/new).'
      negative: 'Sorry to hear that. [Please tell us how we can improve](https://github.com/<USERNAME>/<REPO>/issues/new).'
  comment:
    provider: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''

custom_css:
  - assets/css/custom.css

favicon:
  - /static/favicon.ico